### ISSUE TITLE
portproxy totp feature question

### ISSUE THREAD

**Issue by illusionzhy** [chenzhe07/portproxy#4]
hello ，I want use the totp feature (user connect portproxy with username(mysql -u option) and password(username + (6 bit number from totp) by default);

example:
>first：
> ./portproxy -backend="127.0.0.1:3306" -bind="0.0.0.0:3316"  -conf="conf.cnf" -buffer=16384 
> 2020/04/28 15:59:58 portproxy started.
second：
>  sys-google-totp --secret OJ3UAWO4CIB7M3DQ
>  totp message:
>  secret: OJ3UAWO4CIB7M3DQ
>  671114 (20 second(s) remaining)

starting the program，but I don‘t ’understand the logic
test demo:
>  mysql -u127.0.0.1 -P3316 -utest -ptest671114
>  mysql: [Warning] Using a password on the command line interface can be insecure.
>  ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)

the conf.cnf- [onlineread] configure is  correct，what should i do ？

**Comment by arstercz** [comment]
hi @illusionzhy , it seems that the above error is due to not using the correct version, you should use [totp-version](https://github.com/arstercz/portproxy/archive/v0.1.0.tar.gz), and import [totp-test.sql](https://github.com/arstercz/portproxy/blob/totp/test.sql) to your `conf.cnf - [backend]`.  the following sql should be insert into table `otp_secret`:
```
insert into otp_secret values('test', 'OJ3UAWO4CIB7M3DQ');
```

`portproxy - totp` will get `secret code` from table `otp_secret` by your mysql user, and calculate the `6 digits` of the `secret code`, compare it to the password you  entered.

**note**: only used in test environments.

**Comment by illusionzhy** [comment]
@arstercz   thanks for your help. test completed successfully.
